In [1]:
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json

url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest' 
#Original Sandbox Environment: 'https://sandbox-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
parameters = {
  'start':'1',
  'limit':'15',
  'convert':'USD'
}
headers = {
  'Accepts': 'application/json',
  'X-CMC_PRO_API_KEY': '0ad53085-1cb2-4eb8-ad9e-3ffbd7e56509',
}

session = Session()
session.headers.update(headers)

try:
  response = session.get(url, params=parameters)
  data = json.loads(response.text)
  #print(data)
except (ConnectionError, Timeout, TooManyRedirects) as e:
  print(e)

#NOTE:
# I had to go in and put "jupyter notebook --NotebookApp.iopub_data_rate_limit=1e10"
# Into the Anaconda Prompt to change this to allow to pull data

# If that didn't work try using the local host URL as shown in the video

In [2]:
type(data)

dict

In [3]:
import pandas as pd


#This allows you to see all the columns, not just like 15
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [4]:
#This normalizes the data and makes it all pretty in a dataframe

df = pd.json_normalize(data['data'])
df['timestamp'] = pd.to_datetime('now')
df

<ipython-input-4-c869f2c7fecc>:4: FutureWarning: The parsing of 'now' in pd.to_datetime without `utc=True` is deprecated. In a future version, this will match Timestamp('now') and Timestamp.now()
  df['timestamp'] = pd.to_datetime('now')

,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,total_supply,infinite_supply,platform,cmc_rank,self_reported_circulating_supply,self_reported_market_cap,tvl_ratio,last_updated,quote.USD.price,quote.USD.volume_24h,quote.USD.volume_change_24h,quote.USD.percent_change_1h,quote.USD.percent_change_24h,quote.USD.percent_change_7d,quote.USD.percent_change_30d,quote.USD.percent_change_60d,quote.USD.percent_change_90d,quote.USD.market_cap,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.name,platform.symbol,platform.slug,platform.token_address,timestamp
0,1,Bitcoin,BTC,bitcoin,10221,2010-07-13T00:00:00.000Z,"[mineable, pow, sha-256, store-of-value, state...",2.100000e+07,1.938062e+07,1.938062e+07,False,NaN,1,NaN,NaN,None,2023-05-22T15:33:00.000Z,26870.857931,1.099286e+10,31.0182,-0.450900,-0.241301,-2.013471,-2.295144,-6.156892,9.532304,5.207738e+11,46.3441,5.642880e+11,None,2023-05-22T15:33:00.000Z,NaN,NaN,NaN,NaN,NaN,2023-05-22 15:36:29.706218
1,1027,Ethereum,ETH,ethereum,6929,2015-08-07T00:00:00.000Z,"[pos, smart-contracts, ethereum-ecosystem, coi...",NaN,1.202694e+08,1.202694e+08,True,NaN,2,NaN,NaN,None,2023-05-22T15:33:00.000Z,1815.950542,4.406769e+09,33.5670,-0.283050,0.145399,-0.655960,-2.674982,-1.413360,8.861550,2.184033e+11,19.4462,2.184033e+11,None,2023-05-22T15:33:00.000Z,NaN,NaN,NaN,NaN,NaN,2023-05-22 15:36:29.706218
2,825,Tether,USDT,tether,53860,2015-02-25T00:00:00.000Z,"[payments, stablecoin, asset-backed-stablecoin...",NaN,8.291908e+10,8.609064e+10,True,NaN,3,NaN,NaN,None,2023-05-22T15:33:00.000Z,1.000002,1.718965e+10,32.9945,-0.007235,-0.041216,-0.083425,-0.027294,-0.185479,-0.016165,8.291928e+10,7.3830,8.609085e+10,None,2023-05-22T15:33:00.000Z,1027.0,Ethereum,ETH,ethereum,0xdac17f958d2ee523a2206206994597c13d831ec7,2023-05-22 15:36:29.706218
3,1839,BNB,BNB,bnb,1385,2017-07-25T00:00:00.000Z,"[marketplace, centralized-exchange, payments, ...",NaN,1.558582e+08,1.558582e+08,False,NaN,4,NaN,NaN,None,2023-05-22T15:33:00.000Z,309.715983,3.447519e+08,12.8548,-0.001597,-0.144221,-1.835388,-5.943904,-6.062254,-1.183933,4.827179e+10,4.2980,4.827179e+10,None,2023-05-22T15:33:00.000Z,NaN,NaN,NaN,NaN,NaN,2023-05-22 15:36:29.706218
4,3408,USD Coin,USDC,usd-coin,12578,2018-10-08T00:00:00.000Z,"[medium-of-exchange, stablecoin, asset-backed-...",NaN,2.954574e+10,2.954574e+10,False,NaN,5,NaN,NaN,None,2023-05-22T15:33:00.000Z,0.999871,2.436109e+09,45.9394,-0.004487,-0.016760,-0.053069,-0.039039,0.075558,-0.005607,2.954191e+10,2.6303,2.954191e+10,None,2023-05-22T15:33:00.000Z,1027.0,Ethereum,ETH,ethereum,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,2023-05-22 15:36:29.706218
5,52,XRP,XRP,xrp,951,2013-08-04T00:00:00.000Z,"[medium-of-exchange, enterprise-solutions, arr...",1.000000e+11,5.187315e+10,9.998893e+10,False,NaN,6,NaN,NaN,None,2023-05-22T15:33:00.000Z,0.457895,9.023890e+08,111.1727,-0.441303,-1.599671,7.177162,-2.622976,2.313437,17.387431,2.375246e+10,2.1144,4.578951e+10,None,2023-05-22T15:33:00.000Z,NaN,NaN,NaN,NaN,NaN,2023-05-22 15:36:29.706218
6,2010,Cardano,ADA,cardano,790,2017-10-01T00:00:00.000Z,"[dpos, pos, platform, research, smart-contract...",4.500000e+10,3.486312e+10,3.581044e+10,False,NaN,7,NaN,NaN,None,2023-05-22T15:33:00.000Z,0.367090,1.769585e+08,70.1527,-0.351660,1.092885,-1.057713,-7.602763,-3.655769,-6.387552,1.279789e+10,1.1393,1.651904e+10,None,2023-05-22T15:33:00.000Z,NaN,NaN,NaN,NaN,NaN,2023-05-22 15:36:29.706218
7,74,Dogecoin,DOGE,dogecoin,711,2013-12-15T00:00:00.000Z,"[mineable, pow, scrypt, medium-of-exchange, me...",NaN,1.394515e+11,1.394515e+11,True,NaN,8,NaN,NaN,None,2023-05-22T15:33:00.000Z,0.072901,2.293048e+08,88.8650,-0.234720,-0.601925,0.272331,-9.176415,-6.714804,-15.408656,1.016620e+10,0.9052,1.016620e+10,None,2023-05-22T15:33:00.000Z,NaN,NaN,NaN,NaN,NaN,2023-05-22 15:36:29.706218
8,3890,Polygon,MATIC,polygon,709,2019-04-28T00:00:00.000Z,"[platform, enterprise-solutions, zero-knowledg...",1.000000e+10,9.279469e+09,1.000000e+10,False,NaN,9,NaN,NaN,None,2023-05-22T15:33:00.000Z,0.865122,2.430517e+08,28.5485,-0.242406,-0.890340,-0.395491,-15.208609,-24.558152,-37.395230,8.027877e+09,0.7148,8.651225e+09,None,2023-05-22T15:33:00.000Z,NaN,NaN,NaN,NaN,NaN,2023-05-22 15:36:29.706218
9,5426,Solana,SOL,solana,463,2020-04-10T00:00:00.000Z,"[pos, platform, solana-ecosystem, cms-holdings...",NaN,3.960874e+08,5.483051e+08,True,NaN,10,NaN,NaN,None,2023-05-22T15:33:00.000Z,19.644400,2.635608e+08,101.3933,-0.725732,-2.607161,-8.302038,-9.209611,-12.348743,-21.359010,7.780899e+09,0.6928,1.077112e+10,None,2023-05-22T15:33:00.000Z,NaN,NaN,NaN,NaN,NaN,2023-05-22 15:36:29.706218
10,1958,TRON,TRX,tron,759,2017-09-13T00:00:00.000Z,"[media, payments, tron-ecosystem]",NaN,9.033818e+10,9.033837e+10,True,NaN,11,7.165966e+10,5.640902e+09,None,2023-05-22T15:33:00.000Z,0.078718,4.253192e+08,44.1352,-0.183413,3.776698,12.021017,20.106200,22.650673,12.108317,7.111237e+09,0.6332,7.111252e+09,None,2023-05-22T15:33:00.000Z,NaN,NaN,NaN,NaN,NaN,2023-05-22 15:36:29.706218
11,2,Litecoin,LTC,litecoin,912,2013-04-28T00:00:00.000Z,"[mineable, pow, scrypt, medium-of-exchange]",8.400000e+07,7.297620e+07,8.400000e+07,False,NaN,12,NaN,NaN,None,2023-05-22T15:33:00.000Z,91.106624,4.236056e+08,23.4206,-0.331662,-1.341967,3.299039,4.801788,-2.007405,-2.340178,6.648615e+09,0.5920,7.652956e+09,None,2023-05-22T15:33:00.000Z,NaN,NaN,NaN,NaN,NaN,2023-05-22 15:36:29.706218
12,6636,Polkadot,DOT,polkadot-new,502,2020-08-19T00:00:00.000Z,"[substrate, polkadot, binance-chain, polkadot-...",NaN,1.186203e+09,1.315682e+09,True,NaN,13,NaN,NaN,None,2023-05-22T15:33:00.000Z,5.305483,9.498606e+07,16.7935,-0.126996,-0.663036,-1.546018,-10.922177,-16.417199,-26.994358,6.293380e+09,0.5603,6.980329e+09,None,2023-05-22T15:33:00.000Z,NaN,NaN,NaN,NaN,NaN,2023-05-22 15:36:29.706218
13,4687,Binance USD,BUSD,binance-usd,6786,2019-09-20T00:00:00.000Z,"[stablecoin, asset-backed-stablecoin, binance-...",NaN,5.499802e+09,5.499802e+09,True,NaN,14,NaN,NaN,None,2023-05-22T15:33:00.000Z,0.999942,1.781794e+09,35.2527,0.003134,-0.019457,-0.060962,-0.038174,-0.001194,-0.037863,5.499483e+09,0.4897,5.499483e+09,None,2023-05-22T15:33:00.000Z,1839.0,BNB,BNB,bnb,BUSD-BD1,2023-05-22 15:36:29.706218
14,5994,Shiba Inu,SHIB,shiba-inu,526,2020-08-01T00:00:00.000Z,"[memes, ethereum-ecosystem, doggone-doggerel]",NaN,5.895343e+14,5.895977e+14,False,NaN,15,NaN,NaN,None,2023-05-22T15:33:00.000Z,0.000009,1.506573e+08,156.5144,-0.214396,1.722486,-0.919608,-15.126958,-19.357006,-32.791464,5.181619e+09,0.4614,5.182177e+09,None,2023-05-22T15:33:00.000Z,1027.0,Ethereum,ETH,ethereum,0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce,2023-05-22 15:36:29.706218

In [5]:

def api_runner():
    global df
    url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest' 
    #Original Sandbox Environment: 'https://sandbox-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
    parameters = {
      'start':'1',
      'limit':'15',
      'convert':'USD'
    }
    headers = {
      'Accepts': 'application/json',
      'X-CMC_PRO_API_KEY': '0ad53085-1cb2-4eb8-ad9e-3ffbd7e56509',
    }

    session = Session()
    session.headers.update(headers)

    try:
      response = session.get(url, params=parameters)
      data = json.loads(response.text)
      #print(data)
    except (ConnectionError, Timeout, TooManyRedirects) as e:
      print(e)

#NOTE:
# I had to go in and put "jupyter notebook --NotebookApp.iopub_data_rate_limit=1e10"
# Into the Anaconda Prompt to change this to allow to pull data
    
    # Use this if you just want to keep it in a dataframe
    df2 = pd.json_normalize(data['data'])
    df2['Timestamp'] = pd.to_datetime('now')
    df = df.append(df2)


    # Use this if you want to create a csv and append data to it
    #df = pd.json_normalize(data['data'])
    #df['timestamp'] = pd.to_datetime('now')
    #df

    #if not os.path.isfile(r'C:\Users\alexf\OneDrive\Documents\Python Scripts\API.csv'):
        #df.to_csv(r'C:\Users\alexf\OneDrive\Documents\Python Scripts\API.csv', header='column_names')
    #else:
        #df.to_csv(r'C:\Users\alexf\OneDrive\Documents\Python Scripts\API.csv', mode='a', header=False)
        
    #Then to read in the file: df = pd.read_csv(r'C:\Users\alexf\OneDrive\Documents\Python Scripts\API.csv')

# If that didn't work try using the local host URL as shown in the video

In [6]:
import os 
from time import time
from time import sleep

for i in range(333):
    api_runner()
    print('API Runner completed')
    sleep(60) #sleep for 1 minute
exit()

<ipython-input-5-db5aaff1b24d>:31: FutureWarning: The parsing of 'now' in pd.to_datetime without `utc=True` is deprecated. In a future version, this will match Timestamp('now') and Timestamp.now()
  df2['Timestamp'] = pd.to_datetime('now')
<ipython-input-5-db5aaff1b24d>:32: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df2)

API Runner completed

<ipython-input-5-db5aaff1b24d>:31: FutureWarning: The parsing of 'now' in pd.to_datetime without `utc=True` is deprecated. In a future version, this will match Timestamp('now') and Timestamp.now()
  df2['Timestamp'] = pd.to_datetime('now')
<ipython-input-5-db5aaff1b24d>:32: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df2)

API Runner completed

KeyboardInterrupt: ignored

In [7]:
df72 = pd.read_csv(r'C:\Users\alexf\OneDrive\Documents\Python Scripts\API.csv')
df72

FileNotFoundError: ignored

In [ ]:
df

In [ ]:
# One thing I noticed was the scientific notation. I like it, but I want to be able to see the numbers in this case

pd.set_option('display.float_format', lambda x: '%.5f' % x)

In [ ]:
df

In [ ]:
# Now let's look at the coin trends over time

df3 = df.groupby('name', sort=False)[['quote.USD.percent_change_1h','quote.USD.percent_change_24h','quote.USD.percent_change_7d','quote.USD.percent_change_30d','quote.USD.percent_change_60d','quote.USD.percent_change_90d']].mean()
df3

In [ ]:
df4 = df3.stack()
df4

In [ ]:
type(df4)

In [ ]:
df5 = df4.to_frame(name='values')
df5

In [ ]:
df5.count()

In [ ]:
#Because of how it's structured above we need to set an index. I don't want to pass a column as an index for this dataframe
#So I'm going to create a range and pass that as the dataframe. You can make this more dynamic, but I'm just going to hard code it


index = pd.Index(range(90))

# Set the above DataFrame index object as the index
# using set_index() function
df6 = df5.set_index(index)
df6

# If it only has the index and values try doing reset_index like "df5.reset_index()"

In [ ]:
# Change the column name

df7 = df6.rename(columns={'level_1': 'percent_change'})
df7

In [ ]:
df7['percent_change'] = df7['percent_change'].replace(['quote.USD.percent_change_24h','quote.USD.percent_change_7d','quote.USD.percent_change_30d','quote.USD.percent_change_60d','quote.USD.percent_change_90d'],['24h','7d','30d','60d','90d'])
df7

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
sns.catplot(x='percent_change', y='values', hue='name', data=df7, kind='point')

In [ ]:
# Now to do something much simpler
# we are going to create a dataframe with the columns we want

df10 = df[['name','quote.USD.price','timestamp']]
df10 = df10.query("name == 'Bitcoin'")
df10

In [ ]:
sns.set_theme(style="darkgrid")

sns.lineplot(x='timestamp', y='quote.USD.price', data = df10)