<a href="https://colab.research.google.com/github/blackcrowX/Data-Analysis-Projects/blob/main/PYTHON/pokemon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exploratory Data Analysis

<p>For his latest research project, Professor Oak has decided to investigate the defining characteristics of legendary Pokémon to improve our understanding of their temperament. Hearing of our expertise in classification problems, he has enlisted us as the lead researchers.</p>

<p>Our journey begins at the professor's research lab in Pallet Town, Kanto. The first step is to open up the Pokédex, an encyclopaedic guide to 801 Pokémon from all seven generations.</p>

<img src="https://i.pinimg.com/originals/5b/85/c8/5b85c85333cc9aec7caa5f332961da6a.jpg" alt="image all pokemon sorted by colours">
<p><em>Source: <a href="https://www.flickr.com/photos/bagogames/">bagogames</a> on Flickr</em></p>

##Table of Contents
1. [Setup Libraries](#1)
2. [Load Data](#2)
3. [Read Data](#3)
4. [Basic Analysis](#4)
    * [Data Cleaning](#5)
    * [Frequency](#6)
    * [The Strongest and The Weakest](#7)
    * [The Fastest and The Slowest](#8)
    * [Summary](#9)
5. [Data Visualisation](#10)
    * [Count Plot](#11)
    * [Pie Plot](#12)
    * [Box Plot and Violin Plot](#13)
    * [Swarm Flot](#14)
    * [Heat Map](#15)
6. [Conclusion](#16)

## Step 1: Setup Libraries

Import and configure the Python libraries required for the data analysis.

In [ ]:
import numpy as np
import pandas as pd
pd.plotting.register_matplotlib_converters()
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
print("Setup Complete")

Setup Complete

## Step 2: Load Data
Read the data file into `data` either via following options:

Option 1: Upload CSV File

In [ ]:
from google.colab import files
uploaded = files.upload()

In [ ]:
import io
data = pd.read_csv(io.BytesIO(uploaded['file.csv']))

Option 2: Link CSV File

In [ ]:
url = 'https://raw.githubusercontent.com/blackcrowX/Data-Analysis-Portfolio/main/Project-III/pokemon-stats.csv'
data = pd.read_csv(url)

## Step 3: Review Data

Show the first five rows of the data.

In [ ]:
data.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

Show the last five rows of the data.

In [ ]:
data.tail()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,...,NaN,797,107,101,61,steel,flying,999.9,7,1
797,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,NaN,798,59,31,109,grass,steel,0.1,7,1
798,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,...,NaN,799,97,53,43,dark,dragon,888.0,7,1
799,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,800,127,89,79,psychic,NaN,230.0,7,1
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,NaN,801,130,115,65,steel,fairy,80.5,7,1

## Step 4: Order Columns

Show data columns via `.columns()`.

In [ ]:
data.columns

Index(['abilities', 'against_bug', 'against_dark', 'against_dragon',
       'against_electric', 'against_fairy', 'against_fight', 'against_fire',
       'against_flying', 'against_ghost', 'against_grass', 'against_ground',
       'against_ice', 'against_normal', 'against_poison', 'against_psychic',
       'against_rock', 'against_steel', 'against_water', 'attack',
       'base_egg_steps', 'base_happiness', 'base_total', 'capture_rate',
       'classfication', 'defense', 'experience_growth', 'height_m', 'hp',
       'japanese_name', 'name', 'percentage_male', 'pokedex_number',
       'sp_attack', 'sp_defense', 'speed', 'type1', 'type2', 'weight_kg',
       'generation', 'is_legendary'],
      dtype='object')

Order data columns via `.reindex()`.

In [ ]:
data = data.reindex(columns=['name', 'type1', 'type2', 'abilities', 'against_bug', 'against_dark', 'against_dragon',
       'against_electric', 'against_fairy', 'against_fight', 'against_fire',
       'against_flying', 'against_ghost', 'against_grass', 'against_ground',
       'against_ice', 'against_normal', 'against_poison', 'against_psychic',
       'against_rock', 'against_steel', 'against_water', 'attack',
       'base_egg_steps', 'base_happiness', 'base_total', 'capture_rate',
       'classfication', 'defense', 'experience_growth', 'height_m', 'hp',
       'japanese_name', 'percentage_male', 'pokedex_number',
       'sp_attack', 'sp_defense', 'speed', 'weight_kg',
       'generation', 'is_legendary'])

Adjust data index to `"pokedex-number"` via `.set_index()`.

In [ ]:
data.set_index("pokedex_number")

,name,type1,type2,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,...,height_m,hp,japanese_name,percentage_male,sp_attack,sp_defense,speed,weight_kg,generation,is_legendary
pokedex_number,,,,,,,,,,,,,,,,,,,,,
1,Bulbasaur,grass,poison,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,...,0.7,45,Fushigidaneフシギダネ,88.1,65,65,45,6.9,1,0
2,Ivysaur,grass,poison,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,...,1.0,60,Fushigisouフシギソウ,88.1,80,80,60,13.0,1,0
3,Venusaur,grass,poison,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,...,2.0,80,Fushigibanaフシギバナ,88.1,122,120,80,100.0,1,0
4,Charmander,fire,NaN,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,...,0.6,39,Hitokageヒトカゲ,88.1,60,50,65,8.5,1,0
5,Charmeleon,fire,NaN,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,...,1.1,58,Lizardoリザード,88.1,80,65,80,19.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
797,Celesteela,steel,flying,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,...,9.2,97,Tekkaguyaテッカグヤ,NaN,107,101,61,999.9,7,1
798,Kartana,grass,steel,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.0,...,0.3,59,Kamiturugiカミツルギ,NaN,59,31,109,0.1,7,1
799,Guzzlord,dark,dragon,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.0,...,5.5,223,Akuzikingアクジキング,NaN,97,53,43,888.0,7,1
800,Necrozma,psychic,NaN,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.5,...,2.4,97,Necrozmaネクロズマ,NaN,127,89,79,230.0,7,1
801,Magearna,steel,fairy,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,...,1.0,80,Magearnaマギアナ,NaN,130,115,65,80.5,7,1

## Step 5: Data Cleaning

Adjust data index to `id` via Python command.