<a href="https://colab.research.google.com/github/blackcrowX/Data-Analysis-Projects/blob/main/Python/pokemon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exploratory Data Analysis into Pokemon

by [blackcrowX](https://www.kaggle.com/blackcrowX)

<img src="https://64.media.tumblr.com/acf4c4c535c92d0c3dc75afdf2aca536/tumblr_nvvt9i5PX11qdp5k7o1_1280.png"/>
<p align="center"><em>Image 1: Dark Pokemon by <a href="https://pixelatedtakkun.tumblr.com/">Pixelated Takkun</a> on tumblr</em></p>

##Table of Contents

Introduction

Setup
1. [Load Libraries](#1)
2. [Load Data](#2)
3. [Read Data](#3)

Data Cleaning

4. [Basic Analysis](#4)
5. [Data Cleaning](#5)
6. [Frequency](#6)
7. [The Strongest and The Weakest](#7)

Data Analysis

5. [Frequency](#6)
6. [The Strongest and The Weakest](#7)
7. [The Fastest and The Slowest](#8)
8. [Summary](#9)

Data Visualisation

8. [Count Plot](#11)
9. [Pie Plot](#12)
10. [Box Plot and Violin Plot](#13)
11. [Swarm Flot](#14)
12. [Heat Map](#15)

Findings

# Introduction

<p>For his latest research project, Professor Oak has decided to investigate the defining characteristics of dark Pok√©mon to improve our understanding of their temperament. Hearing of our expertise in classification problems, he has enlisted us as the lead researchers.</p>

# Setup

## Step 1: Setup Libraries

Import and configure Python libraries required for data analysis.

In [ ]:
import numpy as np
import pandas as pd
pd.plotting.register_matplotlib_converters()
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
print("Setup Libraries Complete")

Setup Libraries Complete

## Step 2: Load Data
Read the data file into `data` either via following options:

In [ ]:
url = 'https://raw.githubusercontent.com/blackcrowX/Data-Analysis-Projects/main/Datasets/pokemon-stats-gen-1-7.csv'
data = pd.read_csv(url)
print("Load Data Complete")

Load Data Complete

## Step 3: Review Data

Show the first five rows of the data.

In [ ]:
data.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

Show the last five rows of the data.

In [ ]:
data.tail()

,number,name,type1,type2,total,hp,attack,defense,sp_attack,sp_defense,speed,generation,legendary
1067,896,Glastrier,Ice,NaN,580,100,145,130,65,110,30,8,True
1068,897,Spectrier,Ghost,NaN,580,100,65,60,145,80,130,8,True
1069,898,Calyrex,Psychic,Grass,500,100,80,80,80,80,80,8,True
1070,898,Ice Rider Calyrex,Psychic,Ice,680,100,165,150,85,130,50,8,True
1071,898,Shadow Rider Calyrex,Psychic,Ghost,680,100,85,80,165,100,150,8,True

# Data Cleaning

## Step 4: Drop Columns

Show data columns via `.columns()` to know which columns exist.

In [ ]:
data.columns

Index(['number', 'name', 'type1', 'type2', 'total', 'hp', 'attack', 'defense',
       'sp_attack', 'sp_defense', 'speed', 'generation', 'legendary'],
      dtype='object')

Drop excessive columns via `drop()`.

In [ ]:
data = data.drop(['abilities', 'against_bug', 'against_dark', 'against_dragon',
       'against_electric', 'against_fairy', 'against_fight', 'against_fire',
       'against_flying', 'against_ghost', 'against_grass', 'against_ground',
       'against_ice', 'against_normal', 'against_poison', 'against_psychic',
       'against_rock', 'against_steel', 'against_water', 'japanese_name'],axis=1)
print("Drop Columns Complete")

Drop Columns Complete

## Step 5: Order Columns
Show data columns via .columns().

In [ ]:
data.columns

Index(['attack', 'base_egg_steps', 'base_happiness', 'base_total',
       'capture_rate', 'classfication', 'defense', 'experience_growth',
       'height_m', 'hp', 'name', 'percentage_male', 'pokedex_number',
       'sp_attack', 'sp_defense', 'speed', 'type1', 'type2', 'weight_kg',
       'generation', 'is_legendary'],
      dtype='object')

Order data columns via `.reindex()`.

In [ ]:
data = data.reindex(columns=['type1', 'type2','base_total', 
                             'hp', 'attack', 'defense', 
                             'sp_attack', 'sp_defense', 'speed',
                             'base_egg_steps', 'base_happiness', 'capture_rate',
                             'classfication',  'experience_growth', 'height_m',
                             'name', 'percentage_male', 'weight_kg',
                             'pokedex_number', 'generation', 'is_legendary'])
print("Order Columns Complete")

Order Columns Complete

## Step 5: Set Index

Adjust data index to `"pokedex-number"` via `.set_index()`.

In [ ]:
data.set_index("name")

,type1,type2,base_total,hp,attack,defense,sp_attack,sp_defense,speed,base_egg_steps,base_happiness,capture_rate,classfication,experience_growth,height_m,percentage_male,weight_kg,pokedex_number,generation,is_legendary
name,,,,,,,,,,,,,,,,,,,,
Bulbasaur,grass,poison,318,45,49,49,65,65,45,5120,70,45,Seed Pok√©mon,1059860,0.7,88.1,6.9,1,1,0
Ivysaur,grass,poison,405,60,62,63,80,80,60,5120,70,45,Seed Pok√©mon,1059860,1.0,88.1,13.0,2,1,0
Venusaur,grass,poison,625,80,100,123,122,120,80,5120,70,45,Seed Pok√©mon,1059860,2.0,88.1,100.0,3,1,0
Charmander,fire,NaN,309,39,52,43,60,50,65,5120,70,45,Lizard Pok√©mon,1059860,0.6,88.1,8.5,4,1,0
Charmeleon,fire,NaN,405,58,64,58,80,65,80,5120,70,45,Flame Pok√©mon,1059860,1.1,88.1,19.0,5,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Celesteela,steel,flying,570,97,101,103,107,101,61,30720,0,25,Launch Pok√©mon,1250000,9.2,NaN,999.9,797,7,1
Kartana,grass,steel,570,59,181,131,59,31,109,30720,0,255,Drawn Sword Pok√©mon,1250000,0.3,NaN,0.1,798,7,1
Guzzlord,dark,dragon,570,223,101,53,97,53,43,30720,0,15,Junkivore Pok√©mon,1250000,5.5,NaN,888.0,799,7,1
Necrozma,psychic,NaN,600,97,107,101,127,89,79,30720,0,3,Prism Pok√©mon,1250000,2.4,NaN,230.0,800,7,1
Magearna,steel,fairy,600,80,95,115,130,115,65,30720,0,3,Artificial Pok√©mon,1250000,1.0,NaN,80.5,801,7,1

## Step 6: Change

Adjust data index to `"pokedex-number"` via `.set_index()`.